# Generated by Django 5.1.1 on 2024-09-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_todo_is_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="title",
        ),
        migrations.AddField(
            model_name="todo",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
